package com.hq.acdm.dao.passengerFlowSupervision;

import com.hq.acdm.model.passengerFlowSupervision.BoardingPort;
import com.hq.acdm.model.passengerFlowSupervision.HourlyPassengerCountT2;
import org.apache.ibatis.annotations.Select;

import java.util.List;

/**
 * @author LiFaQiang
 * @date 2018/10/23 15:29
 * @Description
 */
public interface BoardingPortMapper {
    @Select({
            "SELECT T1.GATE,T2.FlightNum,T2.PAXSECURITYAREASUM, TO_CHAR(T2.COBT,'HH24:MI') COBT FROM GATE T1 LEFT JOIN ",
            "(SELECT TA.GATE_1 GATE,TA.FLIGHT_NO_IATA FlightNum,count(ta.GATE_1) PAXSECURITYAREASUM,TD.COBT ",
            "FROM DAILY_FLIGHT_MASTER TA INNER JOIN DAILY_PASSENGER_MASTER TB ON TA.FLIGHT_NO_IATA = TB.PAX_FLIGHTNO AND TB.DPERATION_DATE = TA.OPERATIONAL_DATE ",
            "INNER JOIN DAILY_FLIGHT_ADD_DETAILS TD ON TA.FLIGHT_NO_IATA = TD.FLIGHT_NO_IATA AND TA.A_OR_D = TD.A_OR_D AND TA.OPERATIONAL_DATE = TD.OPERATIONAL_DATE AND ",
            "TA.FLIGHT_REPEAT_COUNT = TD.FLIGHT_REPEAT_COUNT WHERE TA.A_OR_D='D' AND TA.ATOT IS NULL AND TB.PAX_SECURITYCHECKTIME IS NOT NULL AND TB.PAX_BOARDINGTIME IS NULL ",
            "AND TB.DPERATION_DATE=to_timestamp(current_date) GROUP BY TA.GATE_1,TA.FLIGHT_NO_IATA,TD.COBT) T2 ON T1.GATE = T2.GATE WHERE T1.terminal='1' order by T1.GATE"
    })
    List<BoardingPort> findGatePassengerSumT1();
    @Select({
            "SELECT T1.GATE,T2.FlightNum,T2.PAXSECURITYAREASUM, TO_CHAR(T2.COBT,'HH24:MI') COBT FROM GATE T1 LEFT JOIN ",
            "(SELECT TA.GATE_1 GATE,TA.FLIGHT_NO_IATA FlightNum,count(ta.GATE_1) PAXSECURITYAREASUM,TD.COBT ",
            "FROM DAILY_FLIGHT_MASTER TA INNER JOIN DAILY_PASSENGER_MASTER TB ON TA.FLIGHT_NO_IATA = TB.PAX_FLIGHTNO AND TB.DPERATION_DATE = TA.OPERATIONAL_DATE ",
            "INNER JOIN DAILY_FLIGHT_ADD_DETAILS TD ON TA.FLIGHT_NO_IATA = TD.FLIGHT_NO_IATA AND TA.A_OR_D = TD.A_OR_D AND TA.OPERATIONAL_DATE = TD.OPERATIONAL_DATE AND ",
            "TA.FLIGHT_REPEAT_COUNT = TD.FLIGHT_REPEAT_COUNT WHERE TA.A_OR_D='D' AND TA.ATOT IS NULL AND TB.PAX_SECURITYCHECKTIME IS NOT NULL AND TB.PAX_BOARDINGTIME IS NULL ",
            "AND TB.DPERATION_DATE=to_timestamp(current_date) GROUP BY TA.GATE_1,TA.FLIGHT_NO_IATA,TD.COBT) T2 ON T1.GATE = T2.GATE WHERE T1.terminal='2' order by T1.GATE"
    })
    List<BoardingPort> findGatePassengerSumT2();
}
