package com.hq.acdm.vo.dynamicFlight;

import lombok.Data;

@Data
public class TLocalFlightInfoVo {

    private String flightIdD ;
    private String flightIdA ;
    private String flnoD ;
    private String flnoA ;
    private String execDateD;
    private String execDateA;
    private String flStatus ;
    private String flStatuscl ;
    private String flStatusA ;
    private String flightTaskA;
    private String flightTask;
    private String airlines ;
    private String craftTypeIcao ;
    private String classification;
    private String regn ;
    private String adepAdesA ;
    private String adepAdesD ;
    private String adepD ;
    private String adesD ;
    private String eldtADate ;
    private String eldtATime ;
    private String aldtADate ;
    private String aldtATime ;
    private String etotDDate ;
    private String etotDTime ;
    private String atotDDate ;
    private String atotDTime ;
    private String atotATime ;
    private String standA ;
    private String standD ;
    private String runwayA ;
    private String runwayD ;
    private String changeTimeA ;
    private String changeTimeD ;
    private String sibt;
    private String sobt;
    private String cobt ;
    private String ctot ;
    private String ttot ;
    private String tobt ;
    private String aTobt ;
    private String iscontrol ;
    private String eibt ;
    private String aibt ;
    private String eobt ;
    private String aobt ;
    private String etdo ;
    private String etdc ;
    private String atdo ;
    private String atdc ;
    private String atdcStatus;
    private String etfo ;
    private String etfc ;
    private String atfo ;
    private String atfc ;
    private String esct ;
    private String efct ;
    private String asct ;
    private String asctStatus ;
    private String afct ;
    private String esc ;
    private String eec ;
    private String asc ;
    private String ascStatus ;
    private String aec ;
    private String esr ;
    private String eer ;
    private String asr ;
    private String asrStatus ;
    private String aer ;
    private String esbt ;
    private String eebt ;
    private String asbt ;
    private String asbtStatus ;
    private String aebt ;
    private String aebtStatus ;
    private String ersl ;
    private String elsw ;
    private String arsl ;
    private String alsw ;
    private String aGrndTsfTm ;
    private String dGrndTsfTm ;
    private String aact;
    private String trdt ;
    private String mpbt ;
    private String mpet ;
    private String isfocusD ;
    private String isfocusA ;
    private String isDeicingD;
    private String reasonFc ;
    private String reasonType ;
    private String reasonsForFelay ;
    private String delayTime;
    private String delayTimeStatus;
    private String qflj;
    private String fxlj;
    private String acdt;
    private String aedt;
    private String reasonsForAuto ;
    private String eldt;
    private String aldt;
    private String etot;
    private String atot;
    private String boarding;
    private String closeDoor;
    private String rollOut;
    private String delayTimeD;

}
